### ISSUE TITLE
refers to missing S3 bucket

### ISSUE THREAD

**Issue by dmrzzz** [awslabs/aws-vpn-monitor#1]
This template currently fails in us-east-2 because the bucket solutions-builder-us-east-2 does not exist

**Comment by gsingh04** [comment]
Thank you for raising the issue,
We apologize for delay in our response. We are currently investigating it and will update you once we resolve the issue

**Comment by groverlalit** [comment]
The issue has been resolved. Please try launching the solution using the [link ](http://docs.aws.amazon.com/solutions/latest/vpn-monitor/deployment.html) again.
Thanks for your valuable feedback.
