### ISSUE TITLE
Missing solution-helper code?

### ISSUE THREAD

**Issue by himadrisingh001** [awslabs/aws-vpn-monitor#2]
https://github.com/awslabs/aws-vpn-monitor/blob/master/cform/vpn-monitor.template#L232 refers to code from solution-helper, which doesn't exists in the git.

Can we please check-in the solution-helper code.

**Comment by gsingh04** [comment]
Hello,
the code is public and provided under Amazon Software License. You can download the code from Amazon S3 bucket itself.
https://s3.amazonaws.com/solutions-us-east-1/library/solution-helper/v1/solution-helper.zip

**Comment by himadrisingh001** [comment]
thanks a lot for your help!
